[package]
name = "pulpo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.33" , features = ["serde"] }
daemonize = "0.5.0"
log = "0.4.20"
notify-rust = "4.10.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_derive = "1.0.196"
serde_json = "1.0.113"
structopt = "0.3.26"
tungstenite = { version = "0.21.0" , features = ["native-tls"] }
url =  { version = "2.5.0", features = ["serde"] }